### ISSUE TITLE
API create survey bugs

### ISSUE THREAD

**Issue by haanh764** [haanh764/surveyapp#26]
Hello, I just have checked the dev branch and there is an error below

`[SQL: INSERT INTO answer_options (multiple_choice_questions_id, text, image) VALUES (%(multiple_choice_questions_id)s, %(text)s, %(image)s)]
api           | [parameters: {'multiple_choice_questions_id': None, 'text': 'Option 1', 'image': None}]
`

The last time I checked it before, it worked fine to create survey. So I don't know is there any change in the recent merges. Can you check this error

**Comment by Rikain** [comment]
Ye, i changed variable name in one place but not in another, I fixed it now, it should work now with the corrected json from argi with only one formBuilder and saved model and key from reqest.

**Comment by haanh764** [comment]
Thank you XD it works well now
